//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace itrent
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", ConfigurationName="itrent.ETADM086SSPortType")]
    public interface ETADM086SSPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        itrent.ACCEPTResponse ACCEPT(itrent.ACCEPTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<itrent.ACCEPTResponse> ACCEPTAsync(itrent.ACCEPTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        itrent.CHK_CONV_NEWResponse CHK_CONV_NEW(itrent.CHK_CONV_NEWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<itrent.CHK_CONV_NEWResponse> CHK_CONV_NEWAsync(itrent.CHK_CONV_NEWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        itrent.CHK_CONV_STATUSResponse CHK_CONV_STATUS(itrent.CHK_CONV_STATUSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<itrent.CHK_CONV_STATUSResponse> CHK_CONV_STATUSAsync(itrent.CHK_CONV_STATUSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        itrent.EXECResponse EXEC(itrent.EXECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<itrent.EXECResponse> EXECAsync(itrent.EXECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        itrent.QUITResponse QUIT(itrent.QUITRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<itrent.QUITResponse> QUITAsync(itrent.QUITRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        itrent.RUN_CONVResponse RUN_CONV(itrent.RUN_CONVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<itrent.RUN_CONVResponse> RUN_CONVAsync(itrent.RUN_CONVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        itrent.RUN_CONV_NEWResponse RUN_CONV_NEW(itrent.RUN_CONV_NEWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<itrent.RUN_CONV_NEWResponse> RUN_CONV_NEWAsync(itrent.RUN_CONV_NEWRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ACCEPT", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class ACCEPTRequest
    {
        
        public ACCEPTRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ACCEPTResponse", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class ACCEPTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public int @return;
        
        public ACCEPTResponse()
        {
        }
        
        public ACCEPTResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CHK_CONV_NEW", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class CHK_CONV_NEWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public string P_QUEUE_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=1)]
        public string P_USER_NM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=2)]
        public string P_USER_PWD;
        
        public CHK_CONV_NEWRequest()
        {
        }
        
        public CHK_CONV_NEWRequest(string P_QUEUE_ID, string P_USER_NM, string P_USER_PWD)
        {
            this.P_QUEUE_ID = P_QUEUE_ID;
            this.P_USER_NM = P_USER_NM;
            this.P_USER_PWD = P_USER_PWD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CHK_CONV_NEWResponse", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class CHK_CONV_NEWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public int @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=1)]
        public string P_STATUS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=2)]
        public string P_LOG_FILE_DATA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=3)]
        public string P_EXC_FILE_DATA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=4)]
        public string P_SUC_FILE_DATA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=5)]
        public string P_ERROR_MSG;
        
        public CHK_CONV_NEWResponse()
        {
        }
        
        public CHK_CONV_NEWResponse(int @return, string P_STATUS, string P_LOG_FILE_DATA, string P_EXC_FILE_DATA, string P_SUC_FILE_DATA, string P_ERROR_MSG)
        {
            this.@return = @return;
            this.P_STATUS = P_STATUS;
            this.P_LOG_FILE_DATA = P_LOG_FILE_DATA;
            this.P_EXC_FILE_DATA = P_EXC_FILE_DATA;
            this.P_SUC_FILE_DATA = P_SUC_FILE_DATA;
            this.P_ERROR_MSG = P_ERROR_MSG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CHK_CONV_STATUS", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class CHK_CONV_STATUSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public string P_QUEUE_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=1)]
        public string P_USER_NM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=2)]
        public string P_USER_PWD;
        
        public CHK_CONV_STATUSRequest()
        {
        }
        
        public CHK_CONV_STATUSRequest(string P_QUEUE_ID, string P_USER_NM, string P_USER_PWD)
        {
            this.P_QUEUE_ID = P_QUEUE_ID;
            this.P_USER_NM = P_USER_NM;
            this.P_USER_PWD = P_USER_PWD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CHK_CONV_STATUSResponse", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class CHK_CONV_STATUSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public int @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=1)]
        public string P_STATUS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=2)]
        public string P_ERROR_MSG;
        
        public CHK_CONV_STATUSResponse()
        {
        }
        
        public CHK_CONV_STATUSResponse(int @return, string P_STATUS, string P_ERROR_MSG)
        {
            this.@return = @return;
            this.P_STATUS = P_STATUS;
            this.P_ERROR_MSG = P_ERROR_MSG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EXEC", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class EXECRequest
    {
        
        public EXECRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EXECResponse", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class EXECResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public int @return;
        
        public EXECResponse()
        {
        }
        
        public EXECResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QUIT", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class QUITRequest
    {
        
        public QUITRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QUITResponse", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class QUITResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public int @return;
        
        public QUITResponse()
        {
        }
        
        public QUITResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RUN_CONV", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class RUN_CONVRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public string P_CONV_TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=1)]
        public string P_CONV_DIR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=2)]
        public string P_CONV_FILE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=3)]
        public string P_PEOPLE_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=4)]
        public string P_FS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=5)]
        public string P_ORG_NAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=6)]
        public string P_USER_NM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=7)]
        public string P_USER_PWD;
        
        public RUN_CONVRequest()
        {
        }
        
        public RUN_CONVRequest(string P_CONV_TYPE, string P_CONV_DIR, string P_CONV_FILE, string P_PEOPLE_ID, string P_FS, string P_ORG_NAME, string P_USER_NM, string P_USER_PWD)
        {
            this.P_CONV_TYPE = P_CONV_TYPE;
            this.P_CONV_DIR = P_CONV_DIR;
            this.P_CONV_FILE = P_CONV_FILE;
            this.P_PEOPLE_ID = P_PEOPLE_ID;
            this.P_FS = P_FS;
            this.P_ORG_NAME = P_ORG_NAME;
            this.P_USER_NM = P_USER_NM;
            this.P_USER_PWD = P_USER_PWD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RUN_CONVResponse", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class RUN_CONVResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public int @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=1)]
        public string P_LOG_FILE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=2)]
        public string P_EXC_FILE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=3)]
        public string P_SUC_FILE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=4)]
        public string P_QUEUE_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=5)]
        public string P_ERROR_MSG;
        
        public RUN_CONVResponse()
        {
        }
        
        public RUN_CONVResponse(int @return, string P_LOG_FILE, string P_EXC_FILE, string P_SUC_FILE, string P_QUEUE_ID, string P_ERROR_MSG)
        {
            this.@return = @return;
            this.P_LOG_FILE = P_LOG_FILE;
            this.P_EXC_FILE = P_EXC_FILE;
            this.P_SUC_FILE = P_SUC_FILE;
            this.P_QUEUE_ID = P_QUEUE_ID;
            this.P_ERROR_MSG = P_ERROR_MSG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RUN_CONV_NEW", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class RUN_CONV_NEWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public string P_CONV_TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=1)]
        public string P_CONV_DIR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=2)]
        public string P_CONV_FILE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=3)]
        public string P_PEOPLE_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=4)]
        public string P_FS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=5)]
        public string P_ORG_NAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=6)]
        public string P_USER_NM;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=7)]
        public string P_USER_PWD;
        
        public RUN_CONV_NEWRequest()
        {
        }
        
        public RUN_CONV_NEWRequest(string P_CONV_TYPE, string P_CONV_DIR, string P_CONV_FILE, string P_PEOPLE_ID, string P_FS, string P_ORG_NAME, string P_USER_NM, string P_USER_PWD)
        {
            this.P_CONV_TYPE = P_CONV_TYPE;
            this.P_CONV_DIR = P_CONV_DIR;
            this.P_CONV_FILE = P_CONV_FILE;
            this.P_PEOPLE_ID = P_PEOPLE_ID;
            this.P_FS = P_FS;
            this.P_ORG_NAME = P_ORG_NAME;
            this.P_USER_NM = P_USER_NM;
            this.P_USER_PWD = P_USER_PWD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RUN_CONV_NEWResponse", WrapperNamespace="urn:uniface:applic:wrapped:services:ETADM086SS", IsWrapped=true)]
    public partial class RUN_CONV_NEWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=0)]
        public int @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=1)]
        public string P_LOG_FILE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=2)]
        public string P_EXC_FILE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=3)]
        public string P_SUC_FILE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=4)]
        public string P_QUEUE_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uniface:applic:wrapped:services:ETADM086SS", Order=5)]
        public string P_ERROR_MSG;
        
        public RUN_CONV_NEWResponse()
        {
        }
        
        public RUN_CONV_NEWResponse(int @return, string P_LOG_FILE, string P_EXC_FILE, string P_SUC_FILE, string P_QUEUE_ID, string P_ERROR_MSG)
        {
            this.@return = @return;
            this.P_LOG_FILE = P_LOG_FILE;
            this.P_EXC_FILE = P_EXC_FILE;
            this.P_SUC_FILE = P_SUC_FILE;
            this.P_QUEUE_ID = P_QUEUE_ID;
            this.P_ERROR_MSG = P_ERROR_MSG;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ETADM086SSPortTypeChannel : itrent.ETADM086SSPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ETADM086SSPortTypeClient : System.ServiceModel.ClientBase<itrent.ETADM086SSPortType>, itrent.ETADM086SSPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        ///<param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ETADM086SSPortTypeClient() : 
                base(ETADM086SSPortTypeClient.GetDefaultBinding(), ETADM086SSPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ETADM086SS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ETADM086SSPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ETADM086SSPortTypeClient.GetBindingForEndpoint(endpointConfiguration), ETADM086SSPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ETADM086SSPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ETADM086SSPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ETADM086SSPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ETADM086SSPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ETADM086SSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public itrent.ACCEPTResponse ACCEPT(itrent.ACCEPTRequest request)
        {
            return base.Channel.ACCEPT(request);
        }
        
        public System.Threading.Tasks.Task<itrent.ACCEPTResponse> ACCEPTAsync(itrent.ACCEPTRequest request)
        {
            return base.Channel.ACCEPTAsync(request);
        }
        
        public itrent.CHK_CONV_NEWResponse CHK_CONV_NEW(itrent.CHK_CONV_NEWRequest request)
        {
            return base.Channel.CHK_CONV_NEW(request);
        }
        
        public System.Threading.Tasks.Task<itrent.CHK_CONV_NEWResponse> CHK_CONV_NEWAsync(itrent.CHK_CONV_NEWRequest request)
        {
            return base.Channel.CHK_CONV_NEWAsync(request);
        }
        
        public itrent.CHK_CONV_STATUSResponse CHK_CONV_STATUS(itrent.CHK_CONV_STATUSRequest request)
        {
            return base.Channel.CHK_CONV_STATUS(request);
        }
        
        public System.Threading.Tasks.Task<itrent.CHK_CONV_STATUSResponse> CHK_CONV_STATUSAsync(itrent.CHK_CONV_STATUSRequest request)
        {
            return base.Channel.CHK_CONV_STATUSAsync(request);
        }
        
        public itrent.EXECResponse EXEC(itrent.EXECRequest request)
        {
            return base.Channel.EXEC(request);
        }
        
        public System.Threading.Tasks.Task<itrent.EXECResponse> EXECAsync(itrent.EXECRequest request)
        {
            return base.Channel.EXECAsync(request);
        }
        
        public itrent.QUITResponse QUIT(itrent.QUITRequest request)
        {
            return base.Channel.QUIT(request);
        }
        
        public System.Threading.Tasks.Task<itrent.QUITResponse> QUITAsync(itrent.QUITRequest request)
        {
            return base.Channel.QUITAsync(request);
        }
        
        public itrent.RUN_CONVResponse RUN_CONV(itrent.RUN_CONVRequest request)
        {
            return base.Channel.RUN_CONV(request);
        }
        
        public System.Threading.Tasks.Task<itrent.RUN_CONVResponse> RUN_CONVAsync(itrent.RUN_CONVRequest request)
        {
            return base.Channel.RUN_CONVAsync(request);
        }
        
        public itrent.RUN_CONV_NEWResponse RUN_CONV_NEW(itrent.RUN_CONV_NEWRequest request)
        {
            return base.Channel.RUN_CONV_NEW(request);
        }
        
        public System.Threading.Tasks.Task<itrent.RUN_CONV_NEWResponse> RUN_CONV_NEWAsync(itrent.RUN_CONV_NEWRequest request)
        {
            return base.Channel.RUN_CONV_NEWAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ETADM086SS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ETADM086SS))
            {
                return new System.ServiceModel.EndpointAddress("https://ce0369te.webitrent.com/ce0369te_web/srd/ETADM086SS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ETADM086SSPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ETADM086SS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ETADM086SSPortTypeClient.GetEndpointAddress(EndpointConfiguration.ETADM086SS);
        }
        
        public enum EndpointConfiguration
        {
            
            ETADM086SS,
        }
    }
}
